version: '3.4'

services:
  mini-api:
    image: mini-api
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - data:/data/db

volumes:
  data: